### ISSUE TITLE
納品

### ISSUE THREAD

**Issue by Yun-ridukiyua** [konchanksu/SE2_2021#34]
# チェック項目
以下の項目について確認すること

## ドキュメント
自分の担当箇所はその内容、担当外は見た目が崩れていないかを確認すること
画像等適切に表示されるか
pdfが開けるorダウンロードできるか
faviconが表示されているか
自分の担当したページについて、copyright、日付が正しいか

## プログラム
アプリケーションが正しく動くか
make周りが適切に動くか

## pdf
自分の関わる部分でおかしなところがないか

- [x] ドキュメント：ホーム
- [x] ドキュメント：要求仕様書
- [x] ドキュメント：開発計画書
- [x] ドキュメント：基本設計書
- [x] ドキュメント：詳細設計書
- [x] ドキュメント：テスト仕様書
- [x] ドキュメント：テスト結果
- [x] ドキュメント：開発実績
- [x] ドキュメント：プログラム
- [x] ドキュメント：マニュアル
- [x] https://konchanksu.github.io/SE2_2021/index.html でドキュメントが正しく表示されるか
- [x] ソースコード一式
- [x] 開発計画書(pdf)
- [x] 開発実績書(pdf)
- [x] 先生へのお気持ち

**Comment by Kunoshita** [comment]
機能性テストの誤字
・「。。」
・「確確認」
修正お願いします。

**Comment by Kunoshita** [comment]
テスト結果の
コピーライトでcreated by が抜けている。

**Comment by Kunoshita** [comment]
開発実績の
樹状整列課題実績報告書v4.7.pdf
が、指定されているファイル名と実際のファイル名が異なるため開けない。

**Comment by Kunoshita** [comment]
樹状整列課題計画書の
目次の
2. プロジェクトタイムマネジメントが
2.1 プロジェクトタイムマネジメントになっている。

**Comment by Kunoshita** [comment]
樹状整列課題計画書の
0. 要旨
「試行錯誤を 繰り返し」
に謎の半角スペース

**Comment by Kunoshita** [comment]
担当分
結合テスト
機能性テストは確認終了
pdfに関しては誤字脱字はこれ以上確認できませんでした。

**Comment by konchanksu** [comment]
https://konchanksu.github.io/SE2_2021/index.html は最後に直すのでその後確認します
それ以外は問題ないように思います

**Comment by NekoZ-Meow** [comment]
いいと思います

**Comment by RyogaYamauchi** [comment]
大丈夫だと思います

**Comment by SugihaM** [comment]
問題ないと思います。
